name: code_base
description: "A new Flutter-Code-Base project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.2
  dio: ^5.4.1
  encrypt: ^5.0.3
  firebase_core: ^2.25.5
  firebase_messaging: ^14.7.17
  flutter_bloc: ^8.1.4
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  package_info_plus: ^5.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
